import { NextResponse } from "next/server";
import { getAuthenticatedUser, requireManager } from "@/lib/serverAuth";
import { getSupabaseAdminClient } from "@/lib/supabaseAdmin";

function cleanString(value) {
  return typeof value === "string" ? value.trim() : "";
}

function normalizeTaskOrder(tasks) {
  if (!Array.isArray(tasks)) {
    return [];
  }

  return tasks
    .map((task, index) => ({
      taskId: task?.taskId,
      sortOrder: Number.isFinite(Number(task?.sortOrder)) ? Number(task.sortOrder) : index,
    }))
    .filter((task) => task.taskId);
}

async function getManagerOrganizationId(supabase, user) {
  const { data } = await supabase
    .from("user_account")
    .select("organization_id")
    .eq("user_id", user.id)
    .maybeSingle();

  if (data?.organization_id) {
    return data.organization_id;
  }

  const byEmail = await supabase
    .from("user_account")
    .select("organization_id")
    .eq("email", user.email)
    .maybeSingle();

  return byEmail.data?.organization_id ?? null;
}

// Display name of the person performing the assignment (the manager).
async function getActorName(supabase, user) {
  const { data: profile } = await supabase
    .from("profile")
    .select("full_name")
    .eq("user_id", user.id)
    .maybeSingle();
  if (profile?.full_name) return profile.full_name;

  const { data: account } = await supabase
    .from("user_account")
    .select("username, email")
    .eq("user_id", user.id)
    .maybeSingle();
  return account?.username || account?.email || "Manager";
}

// Record a task → employee assignment in the allocation history.
async function recordAssignment(supabase, { taskId, userId, assignedBy }) {
  if (!taskId || !userId) return;
  await supabase.from("task_assignment").insert({
    task_id: taskId,
    user_id: userId,
    assigned_by: assignedBy || "Manager",
    assigned_at: new Date().toISOString(),
    status: "Assigned",
  });
}

async function ensureNewTaskGroup(supabase, organizationId) {
  const { data: existingGroups, error: groupError } = await supabase
    .from("task_group")
    .select("group_id, group_name, sort_order")
    .eq("organization_id", organizationId)
    .order("sort_order", { ascending: true });

  if (groupError) {
    throw new Error(groupError.message);
  }

  const existingNewGroup = (existingGroups ?? []).find(
    (group) => cleanString(group.group_name).toLowerCase() === "new",
  );

  if (existingNewGroup) {
    return existingNewGroup.group_id;
  }

  const lastSortOrder = (existingGroups ?? []).reduce((maxOrder, group) => {
    const sortOrder = Number(group.sort_order);
    return Number.isFinite(sortOrder) ? Math.max(maxOrder, sortOrder) : maxOrder;
  }, -1);

  const { data: createdGroup, error: createGroupError } = await supabase
    .from("task_group")
    .insert({
      organization_id: organizationId,
      group_name: "New",
      sort_order: lastSortOrder + 1,
    })
    .select("group_id")
    .single();

  if (createGroupError) {
    throw new Error(createGroupError.message);
  }

  return createdGroup.group_id;
}

async function createInitialOptimusTasks(supabase, { organizationId, userId }) {
  const groupId = await ensureNewTaskGroup(supabase, organizationId);
  const { data: organization } = await supabase
    .from("organization")
    .select("organization_name")
    .eq("organization_id", organizationId)
    .maybeSingle();
  const organizationName = cleanString(organization?.organization_name) || "organization";

  const { data: lastTask } = await supabase
    .from("task")
    .select("sort_order")
    .eq("organization_id", organizationId)
    .order("sort_order", { ascending: false })
    .limit(1)
    .maybeSingle();
  const firstSortOrder = Number.isFinite(Number(lastTask?.sort_order))
    ? Number(lastTask.sort_order) + 1
    : 0;

  const reason = {
    creation: ["Created from organization goals and previous allocation patterns"],
    allocation: ["Ready for skill-based matching when Smart Task Allocation is enabled"],
  };
  const titles = [
    `Clarify ${organizationName} requirements`,
    `Prepare ${organizationName} execution plan`,
    `Review ${organizationName} delivery risks`,
  ];

  const { error } = await supabase.from("task").insert(
    titles.map((title, index) => ({
      organization_id: organizationId,
      group_id: groupId,
      title,
      description: "Generated by Optimus AI.",
      owner_id: userId,
      assigned_to: null,
      status: "Open",
      priority: "Medium",
      source: "optimus_ai",
      ai_state: "active",
      reasons: reason,
      sort_order: firstSortOrder + index,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    })),
  );

  if (error) {
    throw new Error(error.message);
  }
}

export async function GET(request) {
  try {
    const supabase = getSupabaseAdminClient();
    const { user, error: authError } = await requireManager(request, supabase);

    if (authError) {
      return NextResponse.json({ error: authError }, { status: 403 });
    }

    const organizationId = await getManagerOrganizationId(supabase, user);
    let query = supabase
      .from("task")
      .select("*")
      .order("sort_order", { ascending: true })
      .order("created_at", { ascending: true });

    if (organizationId) {
      query = query.eq("organization_id", organizationId);
    }

    const { data, error } = await query;

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    const taskIds = (data ?? []).map((task) => task.task_id).filter(Boolean);
    let latestAssignmentByTaskId = new Map();

    if (taskIds.length) {
      const { data: assignments, error: assignmentError } = await supabase
        .from("task_assignment")
        .select("task_id, assigned_by, assigned_at")
        .in("task_id", taskIds)
        .order("assigned_at", { ascending: false });

      if (assignmentError) {
        return NextResponse.json({ error: assignmentError.message }, { status: 400 });
      }

      for (const assignment of assignments ?? []) {
        if (!latestAssignmentByTaskId.has(assignment.task_id)) {
          latestAssignmentByTaskId.set(assignment.task_id, assignment);
        }
      }
    }

    const visibleTasks = (data ?? []).filter(
      (task) => !["hidden", "dismissed"].includes(String(task.ai_state || "").toLowerCase()),
    );

    const tasks = visibleTasks.map((task) => {
      const latestAssignment = latestAssignmentByTaskId.get(task.task_id);

      return {
        ...task,
        latest_assigned_by: latestAssignment?.assigned_by ?? null,
        latest_assigned_at: latestAssignment?.assigned_at ?? null,
      };
    });

    return NextResponse.json({ tasks });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function POST(request) {
  try {
    const supabase = getSupabaseAdminClient();
    const { user, error: authError } = await getAuthenticatedUser(request, supabase);

    if (authError) {
      return NextResponse.json({ error: authError }, { status: 403 });
    }

    const managerCheck = await requireManager(request, supabase);

    if (managerCheck.error) {
      return NextResponse.json({ error: managerCheck.error }, { status: 403 });
    }

    const organizationId = await getManagerOrganizationId(supabase, user);
    const {
      groupId,
      title,
      description,
      assignedTo,
      assignedBy,
      source,
      aiState,
      reasons: reason,
      status,
      priority,
      startDatetime,
      endDatetime,
    } = await request.json();

    if (!cleanString(title)) {
      return NextResponse.json({ error: "Task title is required." }, { status: 400 });
    }

    if (!organizationId) {
      return NextResponse.json({ error: "Organization ID is required." }, { status: 400 });
    }

    const { data: lastTask } = await supabase
      .from("task")
      .select("sort_order")
      .eq("organization_id", organizationId)
      .order("sort_order", { ascending: false })
      .limit(1)
      .maybeSingle();
    const nextSortOrder = Number.isFinite(Number(lastTask?.sort_order))
      ? Number(lastTask.sort_order) + 1
      : 0;

    const { data: createdTask, error } = await supabase
      .from("task")
      .insert({
        organization_id: organizationId,
        group_id: groupId ?? null,
        title: cleanString(title),
        description: cleanString(description) || null,
        owner_id: user.id,
        assigned_to: assignedTo || null,
        status: cleanString(status) || "Open",
        priority: cleanString(priority) || "Medium",
        start_datetime: startDatetime || null,
        end_datetime: endDatetime || null,
        source: cleanString(source) || "manual",
        ai_state: aiState || null,
        reasons: reason || null,
        sort_order: nextSortOrder,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      })
      .select("task_id")
      .single();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    if (assignedTo) {
      const actor = assignedBy || (await getActorName(supabase, user));
      await recordAssignment(supabase, {
        taskId: createdTask.task_id,
        userId: assignedTo,
        assignedBy: actor,
      });
    }

    return NextResponse.json({ success: true, task: createdTask });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function PATCH(request) {
  try {
    const supabase = getSupabaseAdminClient();
    const { user, error: authError } = await requireManager(request, supabase);

    if (authError) {
      return NextResponse.json({ error: authError }, { status: 403 });
    }

    const body = await request.json();
    const {
      action,
      tasks,
      taskId,
      groupId,
      title,
      description,
      assignedTo,
      assignedBy,
      aiState,
      status,
      priority,
      startDatetime,
      endDatetime,
    } = body;

    if (action === "set-ai-task-visibility") {
      const isEnabled = Boolean(body.enabled);
      const organizationId = await getManagerOrganizationId(supabase, user);
      if (!organizationId) {
        return NextResponse.json({ error: "Organization ID is required." }, { status: 400 });
      }

      const { data: existingAiTasks, error: existingAiError } = await supabase
        .from("task")
        .select("task_id")
        .eq("organization_id", organizationId)
        .eq("source", "optimus_ai")
        .limit(1);

      if (existingAiError) {
        return NextResponse.json({ error: existingAiError.message }, { status: 400 });
      }

      if (isEnabled && !(existingAiTasks ?? []).length) {
        await createInitialOptimusTasks(supabase, {
          organizationId,
          userId: user.id,
        });

        return NextResponse.json({ success: true, created: true });
      }

      const { error: visibilityError } = await supabase
        .from("task")
        .update({
          ai_state: isEnabled ? "active" : "hidden",
          updated_at: new Date().toISOString(),
        })
        .eq("organization_id", organizationId)
        .eq("source", "optimus_ai")
        .in("ai_state", isEnabled ? ["hidden"] : ["active"]);

      if (visibilityError) {
        return NextResponse.json({ error: visibilityError.message }, { status: 400 });
      }

      return NextResponse.json({ success: true });
    }

    if (action === "move") {
      if (!taskId) {
        return NextResponse.json({ error: "Task ID is required." }, { status: 400 });
      }

      const { error: moveError } = await supabase
        .from("task")
        .update({ group_id: groupId ?? null, updated_at: new Date().toISOString() })
        .eq("task_id", taskId);

      if (moveError) {
        return NextResponse.json({ error: moveError.message }, { status: 400 });
      }

      return NextResponse.json({ success: true });
    }

    if (action === "reorder") {
      const orderedTasks = normalizeTaskOrder(tasks);

      if (!orderedTasks.length) {
        return NextResponse.json({ error: "Tasks are required." }, { status: 400 });
      }

      const organizationId = await getManagerOrganizationId(supabase, user);
      const updates = orderedTasks.map((task) =>
        supabase
          .from("task")
          .update({
            sort_order: task.sortOrder,
            updated_at: new Date().toISOString(),
          })
          .eq("task_id", task.taskId)
          .eq("organization_id", organizationId)
      );
      const results = await Promise.all(updates);
      const failedUpdate = results.find((result) => result.error);

      if (failedUpdate?.error) {
        return NextResponse.json({ error: failedUpdate.error.message }, { status: 400 });
      }

      return NextResponse.json({ success: true });
    }

    const taskUpdates = {
      title: cleanString(title),
      description: cleanString(description) || null,
      assigned_to: assignedTo || null,
      status: cleanString(status) || "Open",
      priority: cleanString(priority) || "Medium",
      start_datetime: startDatetime || null,
      end_datetime: endDatetime || null,
      updated_at: new Date().toISOString(),
    };
    // Only change the group when explicitly provided (move between groups).
    if (groupId !== undefined) {
      taskUpdates.group_id = groupId;
    }

    // Detect a real assignment change so we can log it in the allocation history.
    const { data: existingTask } = await supabase
      .from("task")
      .select("assigned_to, source, ai_state")
      .eq("task_id", taskId)
      .maybeSingle();

    if (aiState !== undefined) {
      taskUpdates.ai_state = aiState;
    } else if (
      existingTask?.source === "optimus_ai" &&
      !["accepted", "dismissed"].includes(String(existingTask?.ai_state || "").toLowerCase())
    ) {
      taskUpdates.ai_state = "accepted";
    }

    const { error } = await supabase.from("task").update(taskUpdates).eq("task_id", taskId);

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    if (assignedTo && assignedTo !== existingTask?.assigned_to) {
      const actor = assignedBy || (await getActorName(supabase, user));
      await recordAssignment(supabase, { taskId, userId: assignedTo, assignedBy: actor });
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function DELETE(request) {
  try {
    const supabase = getSupabaseAdminClient();
    const { error: authError } = await requireManager(request, supabase);

    if (authError) {
      return NextResponse.json({ error: authError }, { status: 403 });
    }

    const { searchParams } = new URL(request.url);
    const taskId = searchParams.get("taskId");
    const { error } = await supabase.from("task").delete().eq("task_id", taskId);

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
